### ISSUE TITLE
Pass the preload request parameters for all openyolo APIs.

### ISSUE THREAD

**Issue by tikurahul** [openid/OpenYOLO-Web#54]
Calling methods like `hintsAvailable()` will not send the `preloadRequest` parameters when making the iframe request. Now that the `clientId` parameter is required - we need to pass in `preloadRequest` when available across all openyolo APIs. This will require changes in the API.

**Comment by TMSCH** [comment]
I think we should indeed send the `preloadRequest` for `hintsAvailable()` as the result should be dependent on the parameters passed (esp. `supportedAuthMethods`).

What API changes to do you have in mind though?
